import os

from app.common.path import TOPONYMS_DB_PATH as DEFAULT_TOPONYMS_DB_PATH


TOPONYMS_DB_PATH = os.environ.get("TOPONYMS_DB_PATH", DEFAULT_TOPONYMS_DB_PATH)


NATURAL_VILLAGE_PLACE_TYPE_CODE = "22200"
DEFAULT_POINT_LIMIT = 5000
MAX_POINT_LIMIT = 20000
MAX_BBOX_AREA = 25.0
DEFAULT_NAME_LIMIT = 20
MAX_NAME_LIMIT = 100
